# Generated by Django 3.0.2 on 2020-01-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('room', models.CharField(blank=True, db_index=True, max_length=8)),
                ('faculty', models.CharField(blank=True, db_index=True, max_length=10)),
                ('form_studies', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('group', models.CharField(blank=True, db_index=True, max_length=10)),
                ('sex', models.CharField(blank=True, db_index=True, max_length=2)),
                ('mobile_number', models.BigIntegerField(blank=True, db_index=True, default=None)),
                ('fluorography', models.BooleanField(db_index=True, default=False)),
                ('pediculosis', models.BooleanField(db_index=True, default=False)),
                ('contract_number', models.CharField(blank=True, db_index=True, max_length=10)),
                ('agreement_date', models.DateField(blank=True, default=None)),
                ('registration', models.DateField(blank=True, default=None)),
                ('citizenship', models.CharField(blank=True, db_index=True, max_length=20)),
                ('date_of_birthday', models.DateField(blank=True, default=None)),
                ('place_of_birthday', models.CharField(blank=True, db_index=True, max_length=70)),
                ('document_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('authority', models.CharField(blank=True, max_length=100)),
                ('date_of_issue', models.DateField(blank=True, default=None)),
                ('notatio', models.TextField(blank=True, db_index=True)),
            ],
        ),
    ]
