# Generated by Django 3.0.2 on 2020-04-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all', models.BooleanField(blank=True, null=True)),
                ('men', models.BooleanField(blank=True, null=True)),
                ('women', models.BooleanField(blank=True, null=True)),
                ('free', models.BooleanField(blank=True, null=True)),
                ('busy', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
