# Generated by Django 3.0.2 on 2020-04-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_status',
        ),
        migrations.AddField(
            model_name='student',
            name='bed_status',
            field=models.CharField(blank=True, choices=[('Студент', 'Студент'), ('Заочник', 'Заочник'), ('Семейник', 'Семейник'), ('Расселитель', 'Расселитель'), ('Староста этажа', 'Староста этажа'), ('Актив этажа', 'Актив этажа'), ('Санитарная комиссия', 'Санитарная комиссия'), ('СООПР', 'СООПР'), ('Женское', 'Женское'), ('Мужское', 'Мужское'), ('Занято', 'Занято'), ('Пусто', 'Пусто')], db_index=True, max_length=30, null=True),
        ),
    ]
