# Generated by Django 3.0.2 on 2020-01-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile_number',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
