# Generated by Django 3.0.2 on 2020-01-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_auto_20200121_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile_number',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
