# Generated by Django 3.0.2 on 2020-03-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_student_place_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(blank=True, choices=[('БЮДЖЕТ', 'Бюджет'), ('ПВЗ', 'ПВЗ')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(blank=True, choices=[('М', 'Мужской'), ('Ж', 'Женский')], db_index=True, max_length=2, null=True),
        ),
    ]
