# Generated by Django 3.0.2 on 2020-01-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_auto_20200121_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contract_number',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=10),
        ),
    ]
