# Generated by Django 3.0.2 on 2020-03-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_auto_20200318_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='fluorography',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='form_studies',
            field=models.CharField(blank=True, choices=[('БЮДЖЕТ', 'Бюджет'), ('ПВЗ', 'ПВЗ')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pediculosis',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
