# Generated by Django 3.0.2 on 2020-01-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_auto_20200121_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='agreement_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
