# Generated by Django 3.0.2 on 2020-01-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_auto_20200121_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
