# Generated by Django 3.0.2 on 2020-03-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_auto_20200325_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.CharField(blank=True, db_index=True, max_length=8),
        ),
    ]
