# Generated by Django 3.0.2 on 2020-03-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_auto_20200325_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.IntegerField(blank=True, db_index=True),
        ),
    ]
