# Generated by Django 3.0.2 on 2020-01-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_auto_20200121_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='notatio',
        ),
        migrations.AddField(
            model_name='student',
            name='notation',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
