# Generated by Django 3.0.2 on 2020-01-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_auto_20200121_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fluorography',
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pediculosis',
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
    ]
