# Generated by Django 3.0.2 on 2020-01-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0011_auto_20200121_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='form_studies',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=10),
        ),
    ]
