# Generated by Django 3.0.2 on 2020-01-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0014_auto_20200122_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contract_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
    ]
