# Generated by Django 3.0.2 on 2020-01-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0015_auto_20200122_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fluorography',
            field=models.CharField(blank=True, db_index=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pediculosis',
            field=models.CharField(blank=True, db_index=True, max_length=1, null=True),
        ),
    ]
